@startuml PartialRendering

class ModelingManager
{
    <<Event>>
    + ModelElementAdded(ItemModelElement)
    + ModelElementsAdded(ItemModelElement)
    --
}
abstract class ItemModelElement
{
    + {abstract} AddShapeAround(shapeType)
}
class ItemModelGroupNonRoot
{
    + AddShapeAround(shapeType)
}
class ItemModelGroupoRoot
{
    + AddShapeAround(shapeType)
}
class ItemModelShape
{
    + AddShapeAround(shapeType)
}
class ModelSection3DView
{
    +void PartialRenderingOptinal(enActionType, \n\t ItemModelElement)
}
class PanelSingleviewControl
interface IPanelSingleView
class PanelSingleViewSpatial
class PanelSingleViewEyeShot
class PanelSingleViewControlShapeBuilder
class PanelSingleViewShapeHandler
class SpaModelerCli
class SingleViewportLayoutEx

/'
여기서 부터는 새로 기능 추가된 Class
'/
class PartialRenderingChecker <<C,Orange>>
{
    +bool IsPartialRedering(ModelEditData, enAirViewType, IsRedraw)
}
class PartialRenderingShapeBuilder <<C,Orange>>
{
    <<Construuctor>>
    +PartialRenderingShapeBuilder(IPanelSingleView, \n\tMaterialColorInfoProvider, \n\tIModelElementEditible)
    --
    <<Method>>
    +AddShapePartial(ItemModelElement)
    +DeleteShapePartial(ItemModelElement)
    +BoundBoxCut(List<ItemModelElement>)
    +PartialRender(ItemModelShape)
    +BringToFront(ItemModelElement)
    +BringToBack(ItemModelElement)
    --
}


/'
Class RelationShip
'/
ModelingManager -right-> ItemModelElement
ItemModelElement <|-- ItemModelGroupNonRoot
ItemModelElement <|-- ItemModelGroupoRoot
ItemModelElement <|-- ItemModelShape
ModelExplorerView --> ModelingManager
ModelSection3DView -right-> ModelingManager
ModelSection3DView -down-> PanelSingleviewControl
PanelSingleviewControl *-> IPanelSingleView
IPanelSingleView <|-- PanelSingleViewEyeShot
IPanelSingleView <|-- PanelSingleViewSpatial
PanelSingleviewControl ..> PanelSingleViewControlShapeBuilder
PanelSingleViewControlShapeBuilder --> PanelSingleViewShapeHandler
PanelSingleViewShapeHandler -right-> IPanelSingleView
PanelSingleViewSpatial --> SpaModelerCli
PanelSingleViewEyeShot --> SingleViewportLayoutEx

/'
New Class RelationShip
'/
ModelSection3DView ..> PartialRenderingChecker
ModelSection3DView ..> PartialRenderingShapeBuilder
PartialRenderingShapeBuilder .up.> ItemModelShape
PartialRenderingShapeBuilder --> IPanelSingleView
@enduml
